services:
  - type: web
    name: she-can-foundation-dashboard
    env: node
    plan: free
    buildCommand: |
      npm install
      cd backend && npm install
      cd ../frontend && npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000 